const fs = require("fs");
const xlsx = require("node-xlsx");

const json = {
  Kuaizi: "Kuaizi",
  退出: "Exit",
  个人主页: "home page",
  提示: "Tips",
  请先选择一个元件进行操作: "Please select a component to operate first",
  元件uid参数不能为空: "The element uid parameter cannot be empty",
  元件个数不能超过: "The number of elements must not exceed{num}",
  原生广告视频和叠加层元件总数不能超过8个:
    "Native AD video and overlay layer components total no more than 8",
  请设置元件类型: "Please set the component type",
  "元件类型只能是文案、图片、视频或音频":
    "The component type can only be text, picture, video or audio",
  请设置元件标签: "Please set the component label",
  "文案元件标签只能是文案、按钮、信息、标题或价格":
    "A text element label can only be a text, button, message, title, or price",
  "图片元件标签只能是Logo、产品、模特、文案、按钮、背景、装饰或价格":
    "Picture element labels can only be logos, products, models, copywriters, buttons, backgrounds, decorations or prices",
  "视频元件标签只能是产品、背景或装饰":
    "The video component label can only be a product, background or decoration",
  请先选择一个分组进行操作: "Please select a group to operate first",
  请先选择一个模板进行操作: "Please select a template to operate",
  "创意尚未保存，是否先保存创意？":
    "The creative has not been saved. Do you want to save the idea first?",
  暂无数据: "No data",
  元件超出限制大小: "The component exceeds the size limit",
  请上传mp4文件: "Please upload mp4 file",
  请上传mp3文件: "Please upload mp3 files",
  "格式错误，请上传格式为png、jpg、gif的图片文件":
    "Format error, please upload PNG, JPG , GIF image file",
  不能为空: "Can't be empty",
  请选择: "Please select one",
  请输入文字: "Please enter text",
  元件至少含有一个元素哦: "The element contains at least one element",
  "不可删除, 元件至少含有一个激活元素":
    "Could not be deleted, the element contains at least one actived material",
  "是否删除此素材?": "delete this element?",
  "是否删除此元件?": "Delete this component?",
  "请上传元件/PSD后开始制作": "Please upload a element and go start",
  "如需进行预览，请先制作创意": "Before preview, please add the cretive first",
  正在上传psd: "On uploading PSD",
  "请检查psd文件是否符合要求并刷新重新上传！":
    "Please check whether the PSD file meets the requirements and refresh and upload again!",
  请检查psd文件是否含有空图层:
    "Please check whether the PSD file contains an empty layer",
  请选择正确的psd文件: "Please select the PSD file by require",
  "当前网络已断开，请连接后重试":
    "The current network has been disconnected. Please try again after connecting",
  "确 定": "Confirm",
  "保 存": "Save",
  "取 消": "Cancel",
  "关 闭": "Close",
  "全 选": "SelectAll",
  "反 选": "SelectReverse",
  "删 除": "Delete",
  "跳 过": "Skip",
  个: "",
  宽: "Width",
  高: "Height",
  上: "Up",
  下: "Down",
  左: "Left",
  右: "Right",
  边: "Side",
  秒: "Seconds",
  图片: "Image",
  试试: "Try",
  延迟: "Delay",
  间隔: "Interval",
  距离: "Distance",
  清除: "Clear",
  解析: "Parsing",
  背景: "background",
  上传: "Upload",
  别名: "Alias",
  确定: "Confirm",
  取消: "Cancel",
  查询: "Query",
  全选: "SelectAll",
  重置: "Reset",
  关闭: "Close",
  删除: "delete",
  其他: "other",
  普通: "Common",
  密码: "Password",
  提交: "Commit",
  异常: "Error",
  等待: "Await",
  轮播: "Carousel",
  水平: "Vorizontal",
  垂直: "Vertical",
  样式1: "Style1",
  样式2: "Style2",
  浮层页: "extraPage",
  用户名: "userName",
  轮播图: "Carousel",
  保存中: "In save",
  请填写: "Please input",
  瀑布流: "Waterfall flow",
  秒执行: "Execute",
  中心偏离: "Center deviation",
  出现位置: "Position",
  添加创意: "Add creative",
  动效效果: "Effect of animate",
  时间间隔: "Interval",
  旋转中心: "Center of rotation",
  动效方向: "Effect direction",
  动效时长: "Duration",
  等待时间: "Delay",
  清空动效: "Clear",
  取消预览: "Cancel",
  选择图片: "Select img",
  选择账号: "Select account",
  所有账号: "All account",
  全部项目: "All Project",
  标签过滤: "Tag filter",
  视频封面: "Poster",
  设置圆角: "Set corners",
  正在上传: "Uploading",
  创意名称: "creativeName",
  创意高度: "Creative height",
  修改成功: "Modify successfully",
  创意宽度: "Creative width",
  重新上传: "re-upload",
  轮播创意: "Carousel Creative",
  轮播背景: "Carousel background",
  保存失败: "Save failed",
  继续编辑: "Continue editing",
  必须大于零: "Greater than zero",
  "确认删除？": "Confirm Delete ？",
  请输入内容: "Please input",
  缩略图配置: "Thumbnail config",
  内容暂为空: "The content is empty",
  "请上传元件后开始 落地页 制作":
    "Please upload the component and start making",
  请选择动效: "Please select effect",
  确定删除素材: "Confirm Delete ?",
  正在上传文件: "Uploading",
  正在创建楼层: "Creating Ad",
  正在更新数据: "Updating",
  正在创建创意: "Creating Creative",
  修改元件类别: "Change component type",
  请选择创意组: "Please select the size group",
  元素激活成功: "Is activated",
  元素停用成功: "Is stopped",
  配置悬浮位置: "Set float page position",
  添加淘积木组件: "Add 淘积木 components",
  请选择动效方向: "Effect direction",
  请选择旋转中心: "Center of rotation",
  请输入动效时长: "Effect duration",
  请输入等待时间: "Please enter await time",
  请输入间隔时间: "Please enter Interval",
  请输入延迟时间: "Please enter delay",
  该素材已经存在: "This element already exists",
  "建议格式：jpg": "Suggested format: JPG",
  "正在解析PSD……": "Parsing PSD...",
  母版未添加组件: "No components were added to the master",
  请输入文本信息: "Please enter text information",
  请设置楼层宽度: "Please set Ad width",
  请设置楼层高度: "Please set Ad height",
  请设置楼层名称: "Please set Ad name",
  选择要添加的组件: "Select the component to add",
  "正在加载中......": "loading......",
  正在更新楼层名称: "Updating the Ad name",
  正在更新楼层尺寸: "Updating the Ad size",
  正在更新轮播尺寸: "Updating the carousel size",
  正在更新创意尺寸: "Updating the creative size",
  正在更新创意名称: "Updating the creative name",
  正在更轮播相关信息: "Updating the carousel info",
  上传文件必须是PSD: "The uploaded file must be PSD",
  请设置轮播尺寸宽度: "Please set the carousel width",
  请选择要添加的组件: "Select the component to add",
  请设置轮播尺寸高度: "Please set the carousel height",
  "请输入落地页ID/名称": "Please project ID or name",
  正在上传元素: "Uploading elements【{name}.png】",
  元件中元素类型不统一: "Element types is different",
  psd批量上传处理完成: "PSD batch upload completed",
  "以下文件命名不规范：": "The following files are not properly named:",
  复用配置到其他创意: "Copy configuration to other Creative",
  "建议大小：小于500KB": "Suggest size: less than 500KB",
  最多支持选择个素材: "Maximum support {num}",
  最多只能上传个素材: "Upload only {num}",
  不设置封面默认为第一帧: "Do not set the cover to default to first frame",
  "建议尺寸：视频展示宽高": "Suggest size: video shows width and height",
  "建议宽度为750，高度不限":
    "The Suggest width is 750 with and unlimited height",
  请上传size大于0kb的文件: "Please upload files larger than 0kb",
  "该浮层页暂无创意，请先上传":
    "This float page is empty, please add creative first",
  请上传元件后开始落地页制作: "Please upload the components and go on",
  "创意保存成功，是否退出制作工具?": "Save success, whether to exit ?",
  "当前网络环境不稳定，建议重新上传":
    "The network is not stable, suggest upload again",
  "在wifi环境下自动播放（视频元件）": "Will autoPlay in wifi environment",
  请先创建楼层和创意后开始制作落地页:
    "Please create Ad and creative to making landing pages",
  PSD中包含的元件个数超出限制:
    "The number of components in the PSD exceeds the limit（limit {num})",
  "文件上传异常：请检查文件后重新上传。":
    "File upload exception: please check the file and upload again.",
  "注意: 需要点下面’保存‘按钮才实际生效":
    "Note: to click the ‘save’ button below to actually work",
  "图层中不能含有蒙版，建议删除后重新上传":
    "The layer cannot contain the mask. delete it and upload it again",
  "已将PSD内容添加到当前创意，继续完成创意吧！":
    "PSD content has been added to the current cretive, keep on!",
  "psd含有空图层或不存在图层，建议调整后重新上传":
    "The PSD contains empty layers or no layers. please re-upload after adjustment",
  "注意: 实际投放样式以母版设置为准，本设置仅供内部进行识别":
    "Note: the actual delivery style is subject to the master Settings. This setting is only for reference",
  "PSD图像模式不为‘8位/通道’或者‘RGB颜色’，建议调整后重新上传":
    "The PSD image mode is not ‘8-bit/channel’ or ‘RGB color’. re-upload after adjustment",
  楼: "Ad",
  否: "No",
  是: "Yes",
  已选: "Selected",
  未激活: "Inactive",
  已激活: "Activated",
  已暂停: "Suspended",
  投放中: "In serving",
  系统命名: "System named",
  是否去重: "Remove Duplicates ？",
  全部版本: "All",
  已创版本: "Selected",
  请选择元素: "Please select the element",
  设置图片命名规则: "Set image naming rules",
  "自定义命名（推荐电商使用）": "Custom naming (suggest for e-commerce)",
  确认: "Confirm",
  素材: "Element",
  素材ID: "Element ID",
  上传中: "Uploading",
  商品图: "Goods images",
  待匹配: "To match",
  商品ID: "Goods ID",
  素材图: "Element images",
  自动匹配: "Automatic match",
  手动匹配: "Manual match",
  匹配系数: "Matching coefficient",
  匹配类型: "Matching type",
  全部楼层: "All Ad",
  全部创意: "All creative",
  元素高级筛选: "Element advanced filter",
  保存匹配结果: "Save the match",
  设置匹配完成: "Set match complete",
  请上传excel表: "Please upload excel",
  选择excel文件: "Select excel file",
  修改匹配系数成功: "The matching coefficient was modified successfully",
  上传商品excel表: "Upload product excel",
  共: "Total",
  无: "None",
  激活: "Actived",
  停用: "Stop",
  名称: "Name",
  标签: "Tag",
  可选: "Selectable",
  预览: "Preview",
  保存: "Save",
  序号: "Order",
  刷新: "Refresh",
  选定: "Select",
  楼层: "Ad",
  浮层: "FloatPage",
  显示: "Display",
  所有: "All",
  压缩: "Compress",
  导入: "Import",
  不压缩: "No compress",
  已引用: "Referenced",
  未引用: "No reference",
  已选中: "Selected",
  落地页: "LandingPage",
  购买页: "Purchase page",
  新建页: "New Page",
  未压缩: "No compress",
  已压缩: "Compressed",
  导入成功: "Is imported",
  修改页面: "Modify the page",
  删除成功: "Has Deleted",
  查看数据: "View data",
  批量创建: "Create batch",
  楼层管理: "Ad management",
  版本管理: "Version management",
  监测管理: "Monitor management",
  批量删除: "Batch delete",
  元素筛选: "Element filter ",
  选择创意: "Select the creative",
  已选元素: "Elements selected ",
  当前创意: "The current creative",
  跳转链接: "Skip links",
  以图选择: "Select By pic",
  刷新表格: "Refres table",
  覆盖提示: "Tips of covering",
  素材管理: "Elements management",
  元素绑定: "Element binding",
  "压缩中...": "Is compressed...",
  创意瀑布流: "Creative waterfall",
  替换组合图: "Replace Combination",
  全部已压缩: "All compressed",
  请选择创意: "Please select creative",
  版本组管理: "Version Group management",
  落地页名称: "Landing Page Name",
  落地页列表: "Landing Page list",
  落地页管理: "Landing Page management",
  个轮播组合: "Carousel Combinations",
  请写创意ID: "Please write the creative ID",
  创建组标签: "Create group label",
  添加标签成功: "Tag added successfully",
  落地页瀑布流: "Landing page waterfall flow",
  轮播楼层管理: "Carousel Ad management",
  查看购买页面: "View the purchase page",
  新增轮播组合: "Add casoule combination",
  请输入商品ID: "Please input product ID",
  "状态读取中...": "Status reading...",
  Excel模板下载: "Excel template download",
  上传Excel价格: "Upload Excel price",
  该楼层缺少创意: "Ad has no creative",
  请输入商品组ID: "Product group ID",
  配置淘积木链接: "Configure 淘积木 link",
  选择所有该元素: "Select all of the elements",
  选择创意组合图: "Choose a combination",
  请选择轮播楼层: "Please select carousel",
  请上传excel文件: "Please upload excel file",
  是否删除选中模块: "Delete selected module ?",
  不能选择多个文件: "Cannot select multiple files",
  请先输入商品组ID: "Please enter product group ID",
  "请以http://开头": "Please begin with http://",
  "批量配置/更改链接": "Batch configuration or change link",
  "正在创建中......": "Being created...",
  "第三方代码（曝光）": "Third party code (exposure)",
  跳到本页某创意位置: "Jump to a creative position on this page",
  上传Excel刷新价格: "Upload Excel refresh price",
  复制到本页签所有项: "Copy all items to this TAB",
  "第三方代码（点击）": "Third party code (click)",
  请输入批量创建名称: "Please enter name for batch creation",
  预计会生成个组合: "Expect to generate {num} combinations",
  请选择要复制到的位置: "Select the location to copy to",
  复制到所有页签所有项: "Copy to all tabs",
  当前轮播创意组合数为: "Number of combinations of carousel is",
  请到轮播楼层管理进行: "Please go to the carousel management",
  "是，按照选择创意命名": "Yes, choose creative name",
  复用商品组ID到所有元素: "Copy item group ID to all elements",
  每个楼层至少选择一个组合: "Select at least one combination per Ad",
  请输入可执行的第三方代码: "Please enter executable third party code",
  "否，按照自己选中的继续创建": "No, continue to create as you select",
  复制所有参数到元素所在组合: "Copy all params to the combination of elements",
  必须保存后才能修改版本名称: "Must save before change version name",
  成功应用该商品组ID到当前标签页:
    "Successfully applied the product group ID to the current TAB",
  商品id为空时无法查看购买页链接:
    "Unable to view purchase page link when product id is empty",
  "每个楼层至少保留一个创意，请重新选择":
    "Retain at least one idea per floor, please re-select",
  "确定要复制当前商品组ID到所有标签页？":
    "Copy the current product group ID to all tabs? ",
  "该浮层暂无创意，请先到制作工具进行创建":
    "This float page has no creative, please go to the production tool to create",
  "确定要复制当前元素的所有参数到其所在组合吗？":
    "Copy all parameters of the current element into its composition?",
  "复制到元素所在组合成功，请点击组合监测进行查看":
    "Successfully copied to the combination of elements, please check",
  "系统检测到创意名称存在规律，可以按照创意名称快速创建组标签":
    "The system detects the existence rule of the creative name and can quickly create group labels according to the creative name",
  "注：其他楼层若不存在上诉所选创意名称，则默认选择该楼层全部创意":
    "Note: if the above creative names do not exist on other Ads, all creative names on that floor will be selected by default",
  元: "Yuan",
  至: "To",
  尺寸: "Size",
  管理: "Management",
  面值: "Price",
  搜索: "Search",
  返回: "Return",
  展开: "Expand",
  所属: "Belong",
  发布: "Publish",
  编辑: "Edit",
  添加: "Add",
  PC端: "PC",
  当前共: "Total",
  已配置: "Configured",
  待填写: "Not configured",
  移动端: "Mobile",
  活动ID: "Activity Id",
  已发布: "Published",
  未发布: "unPublish",
  发布中: "In publish",
  创建成功: "Created",
  保存成功: "Saved",
  发布失败: "Publish failed",
  导出格式: "Export format",
  楼层监测: "Ad monitor",
  创意监测: "Creative monitor",
  组合监测: "Combination monitor",
  元素监测: "Element monitor",
  优惠券库: "Coupon library",
  项目名称: "Project name",
  页面类型: "Page type",
  开始制作: "Starting",
  更新时间: "Update time",
  全部类型: "All type",
  绑定对象: "Bind object",
  选择组合: "Select combination",
  选择元素: "Select element",
  导入代码: "Import code",
  投放状态: "Delivery status",
  选取文件: "Select file",
  清空链接: "Clear link",
  高级筛选: "Advanced filter",
  手动填写: "Input manually",
  清除完毕: "Cleared",
  发布成功: "Publish successfully",
  复制成功: "Copy successfully",
  刷新成功: "Refresh successfully",
  激活成功: "Active successfully",
  停用成功: "Stop successfully",
  替换图片: "Replace image",
  退出浮层: "Exist float page",
  显示浮层: "Show float page",
  填写链接: "Input link",
  "匹配成功！": "Match successful! ",
  通天塔账号: "Babel account Number",
  请选择楼层: "Select Ad",
  个页面版本: "Pages version",
  所属版本组: "Version Group",
  拼命加载中: "Loading",
  第三方检测: "Third party testing",
  淘积木状态: "淘积木status",
  版本组名称: "Version group name",
  筷子版本名: "Version name of Kuaizi",
  请更新链接: "Please update link",
  链接更新中: "Updating link",
  请选择版本: "Select version",
  去设置优惠券: "Go set coupons",
  淘积木瀑布流: "淘积木 waterfall flow",
  首次发布时间: "First publish time",
  最后发布时间: "Last publish time",
  重新加载列表: "reload list",
  选择版本移出: "Move out select version",
  复制投放链接: "Copy delivery",
  监测前提条件: "Precondition of monitor",
  批量复制创建: "Bacth copy to create",
  合并为版本组: "Combine as verison group",
  刷新投放数据: "Refresh delivery data",
  请输入活动ID: "Input activity Id",
  页面基本信息: "Basic information",
  "确认删除吗？": "Delete ?",
  "正在激活中...": "In activing...",
  "正在停用中...": "In stopping...",
  请先选择版本组: "Select version first",
  确定清空链接吗: "Clear link ?",
  复制版本组链接: "Copy verison link",
  淘积木落地页名: "淘积木Landing page name",
  当前版本组下有: "Current Version has",
  "选取淘积木母版 ": "Select 淘积木 master Template ",
  请输入通天塔账号: "Input Babel account",
  复制该版本组链接: "Copy version Link",
  "正在移除中......": "Moving out......",
  "添加/合并至版本组": "Add or combine to version group",
  "正在删除中......": "Removing......",
  "正在发布中......": "Publishing......",
  同步淘积木版本状态: "Synchronize 淘积木 status",
  淘积木最后修改时间: "Last modify time of 淘积木",
  请选择要移动到的创意: "Select creative to move",
  "个落地页（其中已发布": "Landing pages(have published",
  上传Excel匹配元素ID: "Upload Excel matched element ID",
  "请填写/选择版本组的名称":
    "Please input or select the name of the version group",
  "版本组更新失败，请重新尝试": "Version group update failed, please retry",
  "确认删除选中版本, 是否继续?":
    "Confirm deleting the selected version. Do you want to continue?",
  "确认复制选中版本, 是否继续?":
    "Confirm to copy the selected version. Do you want to continue?",
  请确保所选的版本都已经保存过:
    "Make sure all selected versions have been saved",
  确定清空所有选中的创意链接吗:
    "Make sure to empty all selected creative links?",
  "复制该版本组通天塔代码 + 链接":
    "Copy this version group‘s Babel code and link",
  成功应用该商品组ID到所有标签页:
    "Successfully applied the product group ID to all tabs",
  部分版本未发布或发布失败或发布中:
    "Partially unpublish or failing to be publish",
  "部分版本发布失败， 请重新进行发布":
    "Partial publish failed, please republish",
  "该版本同时存在于中, 确定要删除吗?":
    "This version exists in{group}, make sure to delete it?",
  版本组中必须至少保留一个激活状态的版本:
    "At least one active version must be retained in the version group",
  "该楼层暂无创意，请先到制作工具进行创建":
    "This Ad has no creative, please go to the production tools to create",
  "其中个元素已经完成监测码ID、跳转l链接ID匹配":
    "There {num} elements have completed the monitoring code ID, jump l link ID matching",
  "将要发布的版本中有部分同时存在于不同版本组中，确定要发布吗？":
    "Some parts of the versions exist in different verison groups at the same time. Are you sure to publish? ",
  "监测代码建议只填写一种,链接优先级为：元素>组合>创意>楼层, 是否继续保存?":
    "The monitoring code suggests filling in only one, The priority is: element > combination > creative > floor, whether to continue to save? ",
  组: "Group",
  源: "Source",
  目标: "Target",
  卡片: "Card",
  增加: "Add",
  全部: "All",
  随机: "Random",
  元素: "element",
  组合: "combind",
  创意: "Creative",
  配置: "Configuration",
  工具: "Tools",
  候选池: "Candidate pool",
  已停用: "Stoped",
  未配置: "Not Config",
  返回工具: "Return to Tools",
  随机生成: "Random generation",
  添加绑定: "Add bind",
  宝贝链接: "Goods link",
  自定义链接: "Custorm link",
  跨创意绑定: "Cross-creative binding",
  创意绑组合: "Creatives binding combinations",
  创意绑元素: "Creatives binding elements",
  组合绑创意: "Combinations binding creative",
  组合绑组合: "Combinations binding combinations",
  组合绑元素: "Combinations bingding elements",
  元素绑创意: "Elements binding creative",
  元素绑组合: "Elements binding combinations",
  元素绑元素: "Elements binding elements",
  查看候选池: "Check candidate pool",
  "请选择模板!": "Select template!",
  生成参数设置: "Generate parameter Settings",
  随机生成组数: "Random number of groups",
  轮播卡片设置: "Carousel card Settings",
  卡片直接录入: "Direct card entry",
  请填写关键字: "Please input in the keyword ",
  绑定关系已生效: "Binding relationship has work",
  绑定关系已失效: "Binding relationship has no work",
  "价格更新成功！": "Price updated successfully!",
  成功加入候选池: "Join candidate pool successfully ",
  跨创意元素绑定: "Binding across creative elements",
  请填写版本组名称: "Please input in version group name",
  是否保存价格更改: "Save price change or not",
  请选择需要绑定的: "Select the binding",
  关键字用逗号隔开: "Keywords separated by commas",
  "请填写落地页名称!": "Please input the name of the landing page!",
  是否删除当前落地页: "Delete landing page ?",
  "该项目名称已经存在!": "The project name already exists!!",
  创意不能直接绑定创意: "Creative can’t be tied directly to creative",
  至少需要保留一个卡片: "Need to keep at least one card",
  已经没有可以获取的组合: "No combinations are available",
  "卡片数不能大于创意数！":
    "The number of card cannot be greater than the number of creative",
  "网络异常，请稍后重试！": "Network error, please try again later!",
  侯选池已有个轮播组合:
    "There are {num} carousel combinations in the candidate pool ",
  保存选中组合并清空侯选池:
    "Save selected combinations and empty the candidate pool ",
  "候选池没有候选组合，请添加后再保存": "No candidate pool, save after adding",
  "此操作将永久删除该绑定关系, 是否继续?":
    "This operation will permanently delete the binding relationship. Do you want to continue? ",
  "注：单个创意元素绑定可能会导致跨创意元素绑定失效":
    "Note: a single binding of a creative element may result in the failure of binding across creative elements",
  上传成功: "Upload successful ",
  Excel模板: "Excel template",
  "请上传Excel文件！": "Please upload Excel file!",
  "商品价格(系统现价)": "Commodity price (current system price)",
  下一步: "Next",
  确认添加: "Confrim add",
  数据看板: "Data board",
  创建时间: "Create time",
  创意组数: "Creative group number",
  创建落地页: "Create landing page",
  新建落地页: "Create landing page",
  落地页类型: "Landing page type",
  普通落地页: "Common landing page",
  淘积木落地页: "淘积木 landing page",
  请选择组合图: "Select combination",
  SKU价格管理: "SKU price management",
  请输入落地页名称: "Please input langding page name",
  "【普通落地页】制作筷子落地页":
    "【common langding page】make kuaizi langding page",
  "【淘积木落地页】制作淘积木手机端落地页":
    "【淘积木landing page 】make 淘积木 langding page",
  请输入密码: "Please input password",
  请输入用户名: "Please input userName",
  例如: "Example",
  最多: "Most",
  最少: "At least",
  注意: "Note",
  宝贝库: "Goods library",
  "店铺ID ": "Store ID ",
  单品规则: "Single product rule",
  店铺规则: "Shop rules",
  月销x件: "Monthly sales{num}",
  移除该版本: "Remove this version",
  当前编辑创意: "Current editorial creative ",
  无线视频链接: "Wireless video link",
  宝贝ID或标题: "Goods ID or title",
  无线店铺装修地址: "Wireless shop decoration address",
  装修后台复制链接即可: "Decoration background copy link is ok",
  "添加无线视频链接，请到 ": "Add wireless video link, go to",
  "上传视频，上传完毕后复制MP4视频链接即可":
    "Upload video, copy MP4 video link after upload",
  "B店、C店铺转化规则合并，采用shopid来拼接":
    "Shop B and shop C transform rules merge and use shopid to splice ",
  "店铺中在无线端自定义的活动页面的链接地址，请到":
    "The link address of the store‘s wireless customized activity page, please go to",
  "为保证站内的无线资源位能够正常识别，请填写无线运营中心":
    " to ensure that the wireless resource bit in the station can be normally identified, please fill in",
  的无线店铺首页或宝贝的链接: "Wireless store home page or baby link",
  矩形: "rectangle",
  通栏: "banner",
  竖幅: "verticalScroll",
  短横幅: "shortBanner",
  横幅: "horizontal",
  短竖幅: "shortVertical",
  元件: "component",
  文案: "Slogan",
  产品: "product",
  模特: "model",
  按钮: "button",
  装饰: "decoration",
  标题: "title",
  价格: "price",
  logo: "logo",
  信息: "text",
  上移一层: "layerForward",
  下移一层: "layerFallback",
  置于顶层: "layerFisrt",
  置于底层: "layerLast",
  取消组合: "combindCancel",
  微调: "tweak",
  属性: "Attribute",
  特效: "Animation",
  视频: "Video",
  音频: "Audio",
  叠加层: "Overlay",
  楼层名称: "AdName",
  创意属性: "Creative attributes",
  楼层宽度: "Floor width",
  楼层高度: "Floor height",
  轮播尺寸宽度: "Carousel size width",
  轮播尺寸高度: "Carousel size height",
  轮播图顶部距离: "Carousel top distance",
  轮播图间距: "Carousel spacing",
  轮播点: "Carousel point",
  轮播点顶部距离: "The top distance of the carousel",
  位置: "Position",
  排版: "Layout",
  描边: "Border",
  行距: "Line height",
  字间距: "Word spacing",
  发散: "Divergence",
  覆盖整个广告: "Cover the entire ad",
  顶部对齐: "Top alignment",
  底部对齐: "Bottom alignment",
  左边对齐: "Left aligned",
  右边对齐: "Right alignment",
  左上角对齐: "Align the top left corner",
  右上角对齐: "Align the top right corner",
  右下角对齐: "Right bottom corner alignment",
  左下角对齐: "Left bottom corner alignment",
  居中对齐: "Center alignment",
  水平居中: "Horizontal centering",
  垂直居中: "Vertically centered",
  与面板同宽: "Same width as the panel",
  与面板同高: "Same as the panel",
  按比例与面板同宽: "Proportional to the same width as the panel",
  按比例与面板同高: "Proportional to the same height as the panel",
  翻转: "Flip",
  无翻转: "No flip",
  水平翻转: "Horizontal flip",
  垂直翻转: "Vertical flip",
  其他设置: "Other settings",
  类型: "Type",
  字数: "Number of words",
  元件设置: "Component settings",
  旋转: "Rotate",
  透明度: "Opacity",
  背景色: "Background color",
  投影: "Projection",
  间距: "Pitch",
  对齐: "Align",
  字体: "Font",
  填充色: "Fill color",
  字体属性: "Font property",
  字体对齐: "Font alignment",
  商品SKU: "Product SKU",
  视频设置: "Video settings",
  自动播放: "Autoplay",
  循环播放: "Loop play",
  开: "On",
  关: "Off",
  静音播放: "Mute play",
  下一播放: "Next play",
  开启悬浮: "Open floating",
  元素设置: "Element setting",
  元素状态: "Element status",
  淡入淡出: "Fade in and out",
  淡入: "Fade in",
  向下淡入: "Fade down",
  向下快速淡入: "Fast fade down",
  向右淡入: "Fade in right",
  向右快速淡入: "Fast fade to the right",
  向左淡入: "Fade in to the left",
  向左快速淡入: "Fast fade into the left",
  向上淡入: "Fade up",
  向上快速淡入: "Fast up quickly",
  淡出: "Fade out",
  向下淡出: "Fade out",
  向下快速淡出: "Fast fade out",
  向左淡出: "Fade out to the left",
  向左快速淡出: "Fast fade to the left",
  向右淡出: "Fade out right",
  向右快速淡出: "Fast fade to the right",
  向上淡出: "Fade up",
  向上快速淡出: "Fast up quickly",
  弹跳类: "Bounce",
  弹跳进入: "Bounce into",
  向下弹跳进入: "Bounce down into",
  向右弹跳进入: "Bounce right into ",
  向左弹跳进入: "Bounce to the left",
  向上弹跳进入: "Bounce up into",
  弹跳退出: "Bounce exit",
  向下弹跳退出: "Bounce up and exit",
  向左弹跳退出: "Bounce left to exit",
  向右弹跳退出: "Bounce right to exit",
  向上弹跳退出: "Bounce up and exit",
  缩放类: "Zoom",
  放大进入: "Zoom in",
  向下放大进入: "Zoom down into ",
  向右放大进入: "Zoom in to the right",
  向左放大进入: "Zoom in to the left",
  向上放大进入: "Zoom up into ",
  缩小退出: "Reduce exit",
  向下缩小退出: "Zoom down to exit",
  向左缩小退出: "Zoom out to the left",
  向右缩小退出: "Zoom out to the right",
  向上缩小退出: "Zoom out and exit",
  旋转类: "Rotate",
  顺时针旋转进入: "Rotate clockwise into",
  从左往下旋入: "Spin left from left",
  从右往下旋入: "Spin right from right",
  从左往上旋入: "Spin from left to top",
  从右往上旋入: "Spin right from right",
  顺时针旋转退出: "Rotate clockwise to exit",
  向左下旋出: "Spin left to the left",
  向右下旋出: "spin right out",
  向左上旋出: "spin left up",
  向右上旋出: "spin right up",
  翻转类: "Flip",
  水平翻转进入: "Flip horizontally into",
  垂直翻转进入: "Flip vertically into",
  水平翻转退出: "Flip horizontally exit",
  垂直翻转退出: "Flip vertically exit",
  强调类: "Strong",
  弹跳: "Bounce",
  闪烁: "Flashing",
  脉冲: "Pulse",
  橡皮筋: "Rubber band",
  左右弱晃动: "Low and weak shaking",
  上下摆动: "Swing up and down",
  缩放摆动: "Zoom swing",
  左右强晃动: "Strongly shaking left and right",
  拉伸抖动: "Stretching jitter",
  自义定动效: "Custom",
  频率: "Frequency",
  出现动效: "There is a motion effect",
  出现: "Appears",
  左入: "Left in",
  右入: "Right in",
  上入: "Up in",
  下入: "Down in",
  放大: "Zoom in",
  隐藏: "Hide",
  左出: "Left out",
  右出: "Right out",
  上出: "Up out",
  下出: "Down out",
  缩小: "Zoom out",
  消失动效: "Disappearing effect",
  消失: "Disappear",
  速度: "Speed",
  快速: "Quick",
  中速: "Medium speed",
  慢速: "Slow",
  一次: "Once",
  持续: "Continue",
  宽度: "\bwidth",
  高度: "\bheight",
  新增创意: "add creative",
  参数输入有误: "param error",
  "创意删除成功!": "Delete Ad success!",
  "广告创建成功!": "Create Ad success !",
  粘贴: "paste",
  复制: "copy",
  上传元件: "Upload component",
  批量上传元件: "Bulk upload component",
  上传PSD: "Upload PSD",
  上传PSD到当前创意: "Upload PSD to current creative",
  上传PSD到当前项目: "Upload PSD to current project",
  缩放: "Zoom",
  实际大小: "Actual size",
  上一步: "Previous",
  显示网格: "Show grid",
  隐藏网格: "Hide Grid",
  锁定: "Lock",
  解锁: "Unlock",
  设置: "Set",
  创意背景设置: "Creative background settings",
  项目背景设置: "Project background settings",
  全屏: "Full screen",
  取消全屏: "Cancel full screen",
  文字: "Text",
  退出预览: "Exit preview",
  有边框: "Has a border",
  无边框: "No border",
  拉伸: "Cover",
  横向: "Horizontal",
  纵向: "Vertical",
  平铺: "Repeat",
  不平铺: "No Repeat",
  保存项目: "Save project"
};

const data = [["简体中文", "英文"]];

for (const key in json) {
  const arr = [];
  arr.push(key);
  arr.push(json[key]);
  data.push(arr);
}

const options = { "!cols": [{ wch: 60 }, { wch: 100 }] };
let buffer = xlsx.build(
  [
    {
      name: "i18n",
      data: data
    }
  ],
  options
);

fs.writeFile("./h5落地页翻译.xlsx", buffer, function(err) {
  if (err) {
    throw err;
  }
  console.log("success");
});
