// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app.proto

package xgtmp_srv_app

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 类似于声明一个类
type AccessId struct {
	AccessId             uint32   `protobuf:"varint,1,opt,name=accessId,proto3" json:"accessId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessId) Reset()         { *m = AccessId{} }
func (m *AccessId) String() string { return proto.CompactTextString(m) }
func (*AccessId) ProtoMessage()    {}
func (*AccessId) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0}
}

func (m *AccessId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessId.Unmarshal(m, b)
}
func (m *AccessId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessId.Marshal(b, m, deterministic)
}
func (m *AccessId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessId.Merge(m, src)
}
func (m *AccessId) XXX_Size() int {
	return xxx_messageInfo_AccessId.Size(m)
}
func (m *AccessId) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessId.DiscardUnknown(m)
}

var xxx_messageInfo_AccessId proto.InternalMessageInfo

func (m *AccessId) GetAccessId() uint32 {
	if m != nil {
		return m.AccessId
	}
	return 0
}

type MobileApplication struct {
	AppName              string   `protobuf:"bytes,1,opt,name=appName,proto3" json:"appName,omitempty"`
	OtherInfo            string   `protobuf:"bytes,2,opt,name=otherInfo,proto3" json:"otherInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MobileApplication) Reset()         { *m = MobileApplication{} }
func (m *MobileApplication) String() string { return proto.CompactTextString(m) }
func (*MobileApplication) ProtoMessage()    {}
func (*MobileApplication) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{1}
}

func (m *MobileApplication) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileApplication.Unmarshal(m, b)
}
func (m *MobileApplication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileApplication.Marshal(b, m, deterministic)
}
func (m *MobileApplication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileApplication.Merge(m, src)
}
func (m *MobileApplication) XXX_Size() int {
	return xxx_messageInfo_MobileApplication.Size(m)
}
func (m *MobileApplication) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileApplication.DiscardUnknown(m)
}

var xxx_messageInfo_MobileApplication proto.InternalMessageInfo

func (m *MobileApplication) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *MobileApplication) GetOtherInfo() string {
	if m != nil {
		return m.OtherInfo
	}
	return ""
}

type AppResponse struct {
	ErrMsg               string             `protobuf:"bytes,1,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	RetCode              int32              `protobuf:"varint,2,opt,name=retCode,proto3" json:"retCode,omitempty"`
	App                  *MobileApplication `protobuf:"bytes,3,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AppResponse) Reset()         { *m = AppResponse{} }
func (m *AppResponse) String() string { return proto.CompactTextString(m) }
func (*AppResponse) ProtoMessage()    {}
func (*AppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{2}
}

func (m *AppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppResponse.Unmarshal(m, b)
}
func (m *AppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppResponse.Marshal(b, m, deterministic)
}
func (m *AppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppResponse.Merge(m, src)
}
func (m *AppResponse) XXX_Size() int {
	return xxx_messageInfo_AppResponse.Size(m)
}
func (m *AppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppResponse proto.InternalMessageInfo

func (m *AppResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *AppResponse) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *AppResponse) GetApp() *MobileApplication {
	if m != nil {
		return m.App
	}
	return nil
}

func init() {
	proto.RegisterType((*AccessId)(nil), "xgtmp.srv.app.AccessId")
	proto.RegisterType((*MobileApplication)(nil), "xgtmp.srv.app.MobileApplication")
	proto.RegisterType((*AppResponse)(nil), "xgtmp.srv.app.AppResponse")
}

func init() { proto.RegisterFile("app.proto", fileDescriptor_e0f9056a14b86d47) }

var fileDescriptor_e0f9056a14b86d47 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x85, 0xed, 0x14, 0xc7, 0xe9, 0x1d, 0xbb, 0x30, 0x0b, 0x2d, 0xc5, 0x45, 0xe9, 0x42, 0x66,
	0x95, 0x45, 0x7d, 0x82, 0x32, 0xba, 0x18, 0x64, 0x14, 0x03, 0x3e, 0x40, 0xa6, 0xbd, 0x8e, 0x85,
	0x4e, 0x73, 0x49, 0xa2, 0xe8, 0xd3, 0xf9, 0x6a, 0x92, 0x92, 0xfa, 0x33, 0x82, 0x6e, 0xba, 0xcb,
	0x49, 0xbe, 0x7c, 0x9c, 0x90, 0x0b, 0x91, 0x24, 0xe2, 0xa4, 0x95, 0x55, 0x2c, 0x7e, 0xdd, 0xda,
	0x1d, 0x71, 0xa3, 0x5f, 0xb8, 0x24, 0xca, 0x2f, 0x60, 0x56, 0x56, 0x15, 0x1a, 0xb3, 0xaa, 0x59,
	0x0a, 0x33, 0xe9, 0xd7, 0x49, 0x90, 0x05, 0x8b, 0x58, 0x7c, 0xe6, 0xfc, 0x06, 0x4e, 0xd6, 0x6a,
	0xd3, 0xb4, 0x58, 0x12, 0xb5, 0x4d, 0x25, 0x6d, 0xa3, 0x3a, 0x96, 0xc0, 0x91, 0x24, 0xba, 0x95,
	0x3b, 0xec, 0xf9, 0x48, 0x0c, 0x91, 0x9d, 0x43, 0xa4, 0xec, 0x13, 0xea, 0x55, 0xf7, 0xa8, 0x92,
	0x49, 0x7f, 0xf6, 0xb5, 0x91, 0x1b, 0x98, 0x97, 0x44, 0x02, 0x0d, 0xa9, 0xce, 0x20, 0x3b, 0x85,
	0x29, 0x6a, 0xbd, 0x36, 0x5b, 0x6f, 0xf1, 0xc9, 0xe9, 0x35, 0xda, 0xa5, 0xaa, 0xb1, 0x57, 0x1c,
	0x8a, 0x21, 0xb2, 0x02, 0x42, 0x49, 0x94, 0x84, 0x59, 0xb0, 0x98, 0x17, 0x19, 0xff, 0xf1, 0x24,
	0xfe, 0xab, 0xa7, 0x70, 0x70, 0xf1, 0x3e, 0x81, 0xb0, 0x24, 0x62, 0x77, 0x10, 0x2f, 0x35, 0x4a,
	0xeb, 0x08, 0xd7, 0x86, 0xfd, 0x7b, 0x3f, 0x4d, 0xf7, 0x88, 0x6f, 0xe5, 0xf3, 0x03, 0x27, 0x7c,
	0xa0, 0x7a, 0x5c, 0xe1, 0x15, 0xb6, 0x38, 0x9e, 0xf0, 0x1a, 0x8e, 0xef, 0x9f, 0x51, 0xbf, 0x0d,
	0xbe, 0xb3, 0x7d, 0xda, 0xff, 0xf2, 0xdf, 0x9a, 0xcd, 0xb4, 0x9f, 0xa0, 0xcb, 0x8f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xeb, 0x3e, 0x9d, 0x40, 0x4e, 0x02, 0x00, 0x00,
}
